/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 649ef4b0-94fa-4d0f-afb8-843e0bbd0137
-/

/-
We have defined the group of almost-sign-preserving permutations (`ASP`) and the slipface function `slipface`. We have proved several properties of the slipface function, including its finiteness (`slipface_finite`), its asymptotic behavior (`slipface_vanishes_at_pos_infty`, `slipface_vanishes_at_neg_infty`, `slipface_blows_up_at_neg_infty`, `slipface_blows_up_at_pos_infty`), and its recurrence relations (`slipface_succ_left`, `slipface_succ_right`). We have also defined the Demazure product `star_slipface` and proved its existence (`star_slipface_exists`) and associativity (`star_slipface_assoc`). Finally, we have proved the duality identity for slipfaces (`slipface_duality_v2`).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
A permutation `f` of `ℤ` is almost-sign-preserving (ASP) if the set of integers `n` such that `n` and `f(n)` have different signs (where 0 is considered positive) is finite.
-/
def IsASP (f : Equiv.Perm ℤ) : Prop :=
  Set.Finite {n | (n < 0) ≠ (f n < 0)}

/-
The group of almost-sign-preserving permutations (ASP). This is the subgroup of permutations `f` such that `IsASP f` holds.
-/
def ASP : Subgroup (Equiv.Perm ℤ) where
  carrier := {f | IsASP f}
  mul_mem' := by
    intro a b ha hb
    have h_diff : {n : ℤ | (n < 0) ≠ ((a * b) n < 0)} ⊆ {n : ℤ | (n < 0) ≠ (b n < 0)} ∪ {n : ℤ | (b n < 0) ≠ (a (b n) < 0)} := by
      intro n hn; contrapose! hn; aesop;
    -- Since the union of two finite sets is finite, we conclude that the set of sign changes for $a * b$ is finite.
    have h_union_finite : Set.Finite {n : ℤ | (n < 0) ≠ (b n < 0)} ∧ Set.Finite {n : ℤ | (b n < 0) ≠ (a (b n) < 0)} := by
      exact ⟨ hb, Set.Finite.preimage ( fun x => by aesop ) ha ⟩;
    exact Set.Finite.subset ( h_union_finite.1.union h_union_finite.2 ) h_diff
  one_mem' := by
    exact Set.finite_empty.subset fun x hx => hx <| by simp +decide ;
  inv_mem' := by
    intro f hf;
    refine' Set.Finite.subset ( hf.image f ) _;
    intro n hn; use f⁻¹ n; aesop;

/-
Checking if `Set.ncard` is available.
-/
#check Set.ncard

/-
The slipface function `s_α(a, b)` counts the number of integers `n ≥ b` such that `α(n) < a`.
-/
/-- The slipface function of a permutation `α`. -/
noncomputable def slipface (α : Equiv.Perm ℤ) (a b : ℤ) : ℕ :=
  Set.ncard {n | n ≥ b ∧ α n < a}

/-
For an almost-sign-preserving permutation `f`, the set of integers `n ≥ b` such that `f(n) < a` is finite.
-/
lemma slipface_finite {f : Equiv.Perm ℤ} (hf : IsASP f) (a b : ℤ) :
    {n | n ≥ b ∧ f n < a}.Finite := by
  -- By definition of ASP, there exists an integer $N$ such that for all $n > N$, $n$ and $f(n)$ have the same sign.
  obtain ⟨N, hN⟩ : ∃ N : ℤ, ∀ n : ℤ, n > N → (n < 0 ↔ f n < 0) := by
    obtain ⟨ N, hN ⟩ := hf.bddAbove;
    exact ⟨ N, fun n hn => Classical.not_not.1 fun h => hn.not_le <| hN <| by tauto ⟩;
  -- Consider the set of integers $n \geq b$ such that $f(n) < a$. Since $f$ is a permutation, this set is bounded above.
  have h_bounded_above : ∃ M : ℤ, ∀ n : ℤ, n ≥ b ∧ f n < a → n ≤ M := by
    have h_bounded_above : Set.Finite {n : ℤ | n ≥ b ∧ f n < a ∧ n > N} := by
      have h_bounded_above : Set.Finite {n : ℤ | n ≥ b ∧ f n < a ∧ n > N ∧ f n ≥ 0} := by
        have h_bounded_above : Set.Finite {m : ℤ | m < a ∧ m ≥ 0} := by
          exact Set.Finite.subset ( Set.finite_Ico 0 a ) fun x hx => ⟨ hx.2, hx.1 ⟩;
        exact Set.Finite.subset ( h_bounded_above.preimage fun n => by aesop ) fun x hx => ⟨ hx.2.1, hx.2.2.2 ⟩;
      have h_bounded_above : Set.Finite {n : ℤ | n ≥ b ∧ f n < a ∧ n > N ∧ f n < 0} := by
        have h_bounded_above : Set.Finite {n : ℤ | n ≥ b ∧ f n < a ∧ n > N ∧ f n < 0 ∧ n < 0} := by
          exact Set.Finite.subset ( Set.finite_Ico b 0 ) fun x hx => ⟨ hx.1, hx.2.2.2.2 ⟩;
        exact h_bounded_above.subset fun x hx => ⟨ hx.1, hx.2.1, hx.2.2.1, hx.2.2.2, by specialize hN x hx.2.2.1; aesop ⟩;
      exact Set.Finite.subset ( Set.Finite.union ‹Set.Finite { n : ℤ | n ≥ b ∧ f n < a ∧ n > N ∧ f n ≥ 0 } › ‹Set.Finite { n : ℤ | n ≥ b ∧ f n < a ∧ n > N ∧ f n < 0 } › ) fun x hx => by cases le_or_gt 0 ( f x ) <;> aesop;
    exact ⟨ Max.max ( N : ℤ ) ( h_bounded_above.bddAbove.choose ), fun n hn => if h : n > N then le_trans ( h_bounded_above.bddAbove.choose_spec ⟨ hn.1, hn.2, h ⟩ ) ( le_max_right _ _ ) else le_trans ( le_of_not_gt h ) ( le_max_left _ _ ) ⟩;
  exact Set.Finite.subset ( Set.finite_Icc _ _ ) fun x hx => ⟨ hx.1, h_bounded_above.choose_spec x hx ⟩

/-
For any integer $a$, the slipface function $s_\alpha(a, \ell)$ becomes 0 for sufficiently large $\ell$.
-/
lemma slipface_vanishes_at_pos_infty {α : Equiv.Perm ℤ} (hα : IsASP α) (a : ℤ) :
    ∃ L, ∀ ℓ ≥ L, slipface α a ℓ = 0 := by
  -- If $\alpha$ is ASP, then for large $n$, $\alpha(n) > 0$.
  have h_pos : ∃ M, ∀ n ≥ M, 0 < α n := by
    -- Since $\alpha$ is ASP, for large $n$, $\alpha(n) > 0$. This follows from the definition of ASP.
    have h_pos_large_n : ∃ M : ℤ, ∀ n ≥ M, 0 ≤ α n := by
      -- Since S is finite, there exists an integer M such that for all n ≥ M, n is not in S.
      obtain ⟨M, hM⟩ : ∃ M : ℤ, ∀ n ≥ M, n ∉ {n : ℤ | (n < 0) ≠ (α n < 0)} := by
        exact Set.Finite.bddAbove hα |> fun ⟨ M, hM ⟩ => ⟨ M + 1, fun n hn h => not_lt_of_ge ( hM h ) hn ⟩;
      exact ⟨ Max.max M 0, fun n hn => not_lt.1 fun contra => hM n ( le_trans ( le_max_left _ _ ) hn ) <| by simp +decide [ not_lt.2 ( le_trans ( le_max_right M 0 ) hn ), contra ] ⟩;
    -- Since $\alpha$ is injective, $\alpha(n) \to \infty$ as $n \to \infty$.
    have h_inj : Function.Injective α := by
      exact α.injective;
    exact ⟨ h_pos_large_n.choose ^ 2 + α.symm 0 ^ 2 + 1, fun n hn => lt_of_le_of_ne ( h_pos_large_n.choose_spec n ( by nlinarith ) ) ( Ne.symm <| by intro H; exact absurd ( h_inj <| show α n = α ( α.symm 0 ) by aesop ) <| by nlinarith ) ⟩;
  -- Since $\alpha$ is injective, $\alpha(n) \to \infty$ as $n \to \infty$.
  have h_inj : ∀ M : ℤ, ∃ N : ℤ, ∀ n ≥ N, α n > M := by
    -- Since $\alpha$ is injective, the set $\{n \geq M \mid \alpha(n) \leq M\}$ is finite.
    have h_finite : ∀ M : ℤ, {n | n ≥ h_pos.choose ∧ α n ≤ M}.Finite := by
      intro M
      have h_finite : Set.Finite (α ⁻¹' (Set.Icc 0 M)) := by
        exact Set.Finite.preimage ( fun x => by aesop ) ( Set.finite_Icc 0 M );
      exact h_finite.subset fun x hx => ⟨ by linarith [ h_pos.choose_spec x hx.1 ], hx.2 ⟩;
    exact fun M => by rcases Set.Finite.bddAbove ( h_finite M ) with ⟨ N, hN ⟩ ; exact ⟨ Max.max N h_pos.choose + 1, fun n hn => not_le.1 fun contra => not_lt_of_ge ( hN ⟨ by linarith [ le_max_right N h_pos.choose ], contra ⟩ ) ( by linarith [ le_max_left N h_pos.choose ] ) ⟩ ;
  unfold slipface;
  exact Exists.elim ( h_inj a ) fun N hN => ⟨ N, fun ℓ hℓ => by rw [ show { n : ℤ | ℓ ≤ n ∧ α n < a } = ∅ by rw [ Set.eq_empty_iff_forall_notMem ] ; intro n hn; linarith [ hN n ( by linarith [ hn.1 ] ), hn.2 ] ] ; norm_num ⟩

/-
For any integer $b$, the slipface function $s_\alpha(\ell, b)$ becomes 0 for sufficiently small $\ell$.
-/
lemma slipface_vanishes_at_neg_infty {α : Equiv.Perm ℤ} (hα : IsASP α) (b : ℤ) :
    ∃ L, ∀ ℓ ≤ L, slipface α ℓ b = 0 := by
  -- Let $m$ be a lower bound for the set $\{\alpha(n) \mid n \ge b\}$.
  obtain ⟨m, hm⟩ : ∃ m : ℤ, ∀ n ≥ b, α n ≥ m := by
    -- The set $\{\alpha(n) \mid n \ge b\}$ is bounded below because $\alpha$ is almost-sign-preserving.
    have h_bounded_below : BddBelow (Set.image α (Set.Ici b)) := by
      have h_bounded_below : Set.Finite {n : ℤ | n ≥ b ∧ α n < 0} := by
        exact?;
      have h_bounded_below : BddBelow (Set.image α {n : ℤ | n ≥ b ∧ α n < 0}) := by
        exact Set.Finite.bddBelow <| h_bounded_below.image _;
      obtain ⟨ M, hM ⟩ := h_bounded_below;
      exact ⟨ Min.min M 0, Set.forall_mem_image.2 fun n hn => by cases lt_or_ge ( α n ) 0 <;> aesop ⟩;
    exact ⟨ h_bounded_below.choose, fun n hn => h_bounded_below.choose_spec ⟨ n, hn, rfl ⟩ ⟩;
  exact ⟨ m - 1, fun ℓ hℓ => by rw [ slipface ] ; exact Set.ncard_def _ ▸ by rw [ show { n | n ≥ b ∧ α n < ℓ } = ∅ by rw [ Set.eq_empty_iff_forall_notMem ] ; intros n hn; linarith [ hm n hn.1, hn.2 ] ] ; norm_num ⟩

/-
For any integer $a$, the slipface function $s_\alpha(a, \ell)$ goes to infinity as $\ell \to -\infty$.
-/
lemma slipface_blows_up_at_neg_infty {α : Equiv.Perm ℤ} (hα : IsASP α) (a : ℤ) :
    ∀ k, ∃ L, ∀ ℓ ≤ L, slipface α a ℓ ≥ k := by
  -- Let $S = \{n \mid \alpha(n) < a\}$. Since $\alpha$ is a bijection, $S$ is infinite.
  set S := {n : ℤ | α n < a}
  have hS_infinite : Set.Infinite S := by
    -- The set $T = \{n \mid n < a\}$ is infinite.
    have hT_infinite : Set.Infinite {n : ℤ | n < a} := by
      exact Set.Iio_infinite a;
    exact hT_infinite.preimage fun n => by aesop;
  intro k
  obtain ⟨L, hL⟩ : ∃ L : ℤ, Set.ncard (S ∩ Set.Ici L) ≥ k := by
    -- Since $S$ is infinite, for any $k$, we can find $k$ distinct elements in $S$.
    obtain ⟨t, ht⟩ : ∃ t : Finset ℤ, t.card = k ∧ ∀ x ∈ t, x ∈ S := by
      have := hS_infinite.exists_subset_card_eq k; tauto;
    -- Let $L$ be the minimum element in $t$.
    obtain ⟨L, hL⟩ : ∃ L : ℤ, ∀ x ∈ t, L ≤ x := by
      exact Finset.bddBelow t;
    use L;
    rw [ ← ht.1, ← Set.ncard_coe_finset ];
    apply_rules [ Set.ncard_le_ncard ] ; aesop_cat;
    have := slipface_finite hα a L;
    exact this.subset fun x hx => ⟨ hx.2, hx.1 ⟩;
  refine' ⟨ L, fun ℓ hℓ => hL.trans _ ⟩;
  apply_rules [ Set.ncard_le_ncard ];
  · exact fun x hx => ⟨ le_trans hℓ hx.2, hx.1 ⟩;
  · exact?

/-
For any integer $b$, the slipface function $s_\alpha(\ell, b)$ goes to infinity as $\ell \to \infty$.
-/
lemma slipface_blows_up_at_pos_infty {α : Equiv.Perm ℤ} (hα : IsASP α) (b : ℤ) :
    ∀ k, ∃ L, ∀ ℓ ≥ L, slipface α ℓ b ≥ k := by
  -- Since $\alpha(\mathbb{Z}_{\ge b})$ is infinite, we can choose a subset of it with size $k$.
  have h_subset : ∀ k : ℕ, ∃ S : Finset ℤ, S.card = k ∧ ∀ x ∈ S, x ≥ b ∧ α x ∈ Set.Ici b := by
    have h_inf : Set.Infinite {n : ℤ | n ≥ b ∧ α n ∈ Set.Ici b} := by
      -- Since $\alpha$ is a permutation, the set $\{n \geq b \mid \alpha(n) < b\}$ is finite.
      have h_finite_neg : Set.Finite {n | n ≥ b ∧ α n < b} := by
        exact?;
      exact Set.Infinite.mono ( fun x hx => by aesop ) ( Set.Infinite.diff ( Set.Ici_infinite b ) h_finite_neg );
    exact fun k => by have := h_inf.exists_subset_card_eq k; tauto;
  intro k;
  obtain ⟨ S, hS₁, hS₂ ⟩ := h_subset k;
  -- Let $L$ be an integer greater than all elements in the image of $S$ under $\alpha$.
  obtain ⟨L, hL⟩ : ∃ L : ℤ, ∀ x ∈ S, α x < L := by
    exact ⟨ ∑ x ∈ S, |α x| + 1, fun x hx => by linarith [ abs_le.mp ( Finset.single_le_sum ( fun x _ => abs_nonneg ( α x ) ) hx ) ] ⟩;
  use L + 1;
  intro ℓ hℓ
  have h_card : Set.ncard {n | n ≥ b ∧ α n < ℓ} ≥ Set.ncard (S : Set ℤ) := by
    apply Set.ncard_le_ncard;
    · exact fun x hx => ⟨ hS₂ x hx |>.1, by linarith [ hL x hx ] ⟩;
    · exact?;
  aesop

/-
The minimum in the definition of the Demazure product exists. Specifically, the function $\ell \mapsto s_\alpha(a, \ell) + s_\beta(\ell, b)$ attains its minimum.
-/
/-- The min-plus product of the slipfaces of two permutations. -/
noncomputable def star_slipface (α β : Equiv.Perm ℤ) (a b : ℤ) : ℕ :=
  sInf {k | ∃ ℓ, k = slipface α a ℓ + slipface β ℓ b}

lemma star_slipface_exists {α β : Equiv.Perm ℤ} (hα : IsASP α) (hβ : IsASP β) (a b : ℤ) :
    ∃ ℓ, star_slipface α β a b = slipface α a ℓ + slipface β ℓ b := by
  have := Nat.sInf_mem ( show { k : ℕ | ∃ ℓ : ℤ, k = slipface α a ℓ + slipface β ℓ b }.Nonempty from ⟨ _, ⟨ 0, rfl ⟩ ⟩ ) ; aesop;

/-
The "delta property" of the slipface function: the second mixed difference of $s_\alpha$ at $(a,b)$ is 1 if $\alpha(b) = a$ and 0 otherwise.
-/
lemma slipface_delta {α : Equiv.Perm ℤ} (hα : IsASP α) (a b : ℤ) :
    (slipface α (a + 1) b - slipface α a b : ℤ) - (slipface α (a + 1) (b + 1) - slipface α a (b + 1) : ℤ) = if α b = a then 1 else 0 := by
  -- Let's simplify the expression using the definitions of slipface.
  have h_simp : ((Set.ncard {n : ℤ | n ≥ b ∧ α n < a + 1}) : ℤ) - ((Set.ncard {n : ℤ | n ≥ b ∧ α n < a}) : ℤ) = (Set.ncard {n : ℤ | n ≥ b ∧ α n = a}) := by
    rw [ show { n | n ≥ b ∧ α n < a + 1 } = { n | n ≥ b ∧ α n < a } ∪ { n | n ≥ b ∧ α n = a } from ?_, @Set.ncard_union_eq ];
    · grind +ring;
    · exact Set.disjoint_left.mpr fun x hx₁ hx₂ => hx₁.2.not_le <| hx₂.2.ge;
    · exact?;
    · have := slipface_finite hα ( a + 1 ) b;
      exact this.subset fun x hx => ⟨ hx.1, by linarith [ hx.2 ] ⟩;
    · ext n; simp +decide [ le_iff_lt_or_eq, or_comm ] ;
      grind
  have h_simp2 : ((Set.ncard {n : ℤ | n ≥ b + 1 ∧ α n < a + 1}) : ℤ) - ((Set.ncard {n : ℤ | n ≥ b + 1 ∧ α n < a}) : ℤ) = (Set.ncard {n : ℤ | n ≥ b + 1 ∧ α n = a}) := by
    rw [ show { n : ℤ | b + 1 ≤ n ∧ ( α n ) < a + 1 } = { n : ℤ | b + 1 ≤ n ∧ ( α n ) < a } ∪ { n : ℤ | b + 1 ≤ n ∧ ( α n ) = a } from ?_, @Set.ncard_union_eq ];
    · grind;
    · exact Set.disjoint_left.mpr fun x hx₁ hx₂ => by linarith [ hx₁.2, hx₂.2 ] ;
    · exact?;
    · exact Set.Finite.subset ( Set.finite_singleton ( α.symm a ) ) fun x hx => by have := α.injective ( by aesop : α x = α ( α.symm a ) ) ; aesop;
    · ext n; simp [Set.mem_union, Set.mem_setOf_eq];
      exact ⟨ fun h => by omega, fun h => by omega ⟩
  generalize_proofs at *;
  cases em ( α b = a ) <;> simp_all +decide [ Set.ncard_eq_toFinset_card' ];
  · -- Since $\alpha(b) = a$, we have $\{n \ge b \mid \alpha(n) = a\} = \{b\}$ and $\{n \ge b + 1 \mid \alpha(n) = a\} = \emptyset$.
    have h_cases : {n : ℤ | b ≤ n ∧ α n = a} = {b} ∧ {n : ℤ | b + 1 ≤ n ∧ α n = a} = ∅ := by
      aesop;
    unfold slipface; aesop;
  · -- Since $\alpha(b) \neq a$, the sets $\{n \geq b \mid \alpha(n) = a\}$ and $\{n \geq b + 1 \mid \alpha(n) = a\}$ are equal.
    have h_eq_sets : {n : ℤ | n ≥ b ∧ α n = a} = {n : ℤ | n ≥ b + 1 ∧ α n = a} := by
      exact Set.ext fun x => ⟨ fun hx => ⟨ lt_of_le_of_ne hx.1 ( Ne.symm <| by aesop ), hx.2 ⟩, fun hx => ⟨ by linarith [ hx.1 ], hx.2 ⟩ ⟩;
    unfold slipface; aesop;

/-
The supremum `M_star` of the set of minimizers for the Demazure product is itself a minimizer.
-/
/-- The maximum ℓ achieving the minimum in the Demazure product. -/
noncomputable def M_star (α β : Equiv.Perm ℤ) (a b : ℤ) : ℤ :=
  sSup {ℓ | slipface α a ℓ + slipface β ℓ b = star_slipface α β a b}

lemma M_star_mem {α β : Equiv.Perm ℤ} (hα : IsASP α) (hβ : IsASP β) (a b : ℤ) :
    slipface α a (M_star α β a b) + slipface β (M_star α β a b) b = star_slipface α β a b := by
  apply le_antisymm;
  · unfold M_star;
    have h_nonempty : {ℓ | slipface α a ℓ + slipface β ℓ b = star_slipface α β a b}.Nonempty := by
      exact star_slipface_exists hα hβ a b |> fun ⟨ ℓ, hℓ ⟩ => ⟨ ℓ, hℓ.symm ⟩;
    have h_bounded_above : BddAbove {ℓ | slipface α a ℓ + slipface β ℓ b = star_slipface α β a b} := by
      have h_bounded_above : ∃ L, ∀ ℓ ≥ L, slipface β ℓ b > star_slipface α β a b := by
        exact?;
      exact ⟨ h_bounded_above.choose, fun x hx => not_lt.1 fun contra => by linarith [ hx.symm, h_bounded_above.choose_spec x contra.le, Nat.zero_le ( slipface α a x ) ] ⟩;
    have := Int.exists_greatest_of_bdd h_bounded_above h_nonempty;
    rw [ show SupSet.sSup { ℓ : ℤ | slipface α a ℓ + slipface β ℓ b = star_slipface α β a b } = this.choose from le_antisymm ( csSup_le ⟨ _, this.choose_spec.1 ⟩ fun x hx => this.choose_spec.2 x hx ) ( le_csSup h_bounded_above this.choose_spec.1 ) ] ; exact this.choose_spec.1.le;
  · exact csInf_le ⟨ 0, by rintro x ⟨ ℓ, rfl ⟩ ; exact Nat.zero_le _ ⟩ ⟨ M_star α β a b, rfl ⟩

/-
Any index $\ell$ that achieves the minimum in the Demazure product is less than or equal to `M_star`.
-/
lemma M_star_is_max {α β : Equiv.Perm ℤ} (hα : IsASP α) (hβ : IsASP β) (a b : ℤ) :
    ∀ ℓ, slipface α a ℓ + slipface β ℓ b = star_slipface α β a b → ℓ ≤ M_star α β a b := by
  -- Let $\ell$ be an index such that $s_\alpha(a, \ell) + s_\beta(\ell, b) = s_{\alpha \star \beta}(a, b)$.
  intro ℓ hℓ
  have h_inf : {ℓ | slipface α a ℓ + slipface β ℓ b = star_slipface α β a b}.Nonempty := by
    exact ⟨ ℓ, hℓ ⟩;
  have h_bounded_above : BddAbove {ℓ | slipface α a ℓ + slipface β ℓ b = star_slipface α β a b} := by
    -- By definition of $M_star$, we know that for any $\ell$ in the set, $\ell \leq M_star$.
    have hM_star_le : ∀ ℓ, slipface α a ℓ + slipface β ℓ b = star_slipface α β a b → ∃ L, ∀ ℓ ≥ L, slipface β ℓ b > star_slipface α β a b := by
      exact?;
    exact ⟨ Classical.choose ( hM_star_le ℓ hℓ ), fun x hx => not_lt.1 fun contra => not_le_of_gt ( Classical.choose_spec ( hM_star_le ℓ hℓ ) x contra.le ) ( by linarith [ hx.symm, show slipface α a x ≥ 0 from Nat.zero_le _ ] ) ⟩;
  exact le_csSup h_bounded_above hℓ

/-
The min-plus product is associative, provided the necessary minimums exist.
-/
/-- The min-plus product of two functions `f, g : ℤ → ℤ → ℕ`. -/
noncomputable def min_plus_product (f g : ℤ → ℤ → ℕ) (a b : ℤ) : ℕ :=
  sInf {k | ∃ ℓ, k = f a ℓ + g ℓ b}

lemma min_plus_product_assoc (f g h : ℤ → ℤ → ℕ)
    (hf : ∀ a b, ∃ ℓ, min_plus_product f g a b = f a ℓ + g ℓ b)
    (hg : ∀ a b, ∃ ℓ, min_plus_product g h a b = g a ℓ + h ℓ b)
    (h_assoc : ∀ a b, ∃ k ℓ, min_plus_product (min_plus_product f g) h a b = f a k + g k ℓ + h ℓ b) :
    min_plus_product (min_plus_product f g) h = min_plus_product f (min_plus_product g h) := by
  funext a b;
  refine' le_antisymm _ _;
  · unfold min_plus_product at *;
    obtain ⟨ k, ℓ, hk ⟩ := h_assoc a b;
    refine' le_csInf _ _;
    · exact ⟨ _, ⟨ k, rfl ⟩ ⟩;
    · rintro _ ⟨ m, rfl ⟩;
      obtain ⟨ n, hn ⟩ := hg m b;
      refine' le_trans ( csInf_le _ ⟨ n, rfl ⟩ ) _;
      · exact ⟨ 0, fun x hx => Nat.zero_le _ ⟩;
      · linarith [ show InfSet.sInf { k : ℕ | ∃ ℓ : ℤ, k = f a ℓ + g ℓ n } ≤ f a m + g m n from Nat.sInf_le ⟨ m, rfl ⟩, show InfSet.sInf { k : ℕ | ∃ ℓ : ℤ, k = g m ℓ + h ℓ b } ≤ g m n + h n b from Nat.sInf_le ⟨ n, rfl ⟩ ];
  · -- By definition of min_plus_product, we know that for any $k$ and $\ell$, we have $f(a, k) + g(k, \ell) + h(\ell, b) \geq \min_plus_product f (min_plus_product g h) a b$.
    have h_min : ∀ k ℓ, f a k + g k ℓ + h ℓ b ≥ min_plus_product f (min_plus_product g h) a b := by
      intros k ℓ
      have h_min : min_plus_product f (min_plus_product g h) a b ≤ f a k + min_plus_product g h k b := by
        exact csInf_le ⟨ 0, by rintro x ⟨ ℓ, rfl ⟩ ; exact Nat.zero_le _ ⟩ ⟨ k, rfl ⟩;
      have h_min : min_plus_product g h k b ≤ g k ℓ + h ℓ b := by
        exact csInf_le ⟨ 0, by rintro x ⟨ ℓ, rfl ⟩ ; positivity ⟩ ⟨ ℓ, rfl ⟩;
      linarith;
    obtain ⟨ k, ℓ, h ⟩ := h_assoc a b; exact h.symm ▸ h_min k ℓ;

/-
The Demazure product `star_slipface α β a ℓ` goes to infinity as `ℓ → -∞`.
-/
lemma star_slipface_blows_up_at_neg_infty {α β : Equiv.Perm ℤ} (hα : IsASP α) (hβ : IsASP β) (a : ℤ) :
    ∀ k, ∃ L, ∀ ℓ ≤ L, star_slipface α β a ℓ ≥ k := by
  -- Since $s_\alpha(a, m_i) < K$, the sequence $m_i$ must be bounded below.
  have h_m_bounded_below : ∀ k, ∃ M, ∀ m, slipface α a m < k → m ≥ M := by
    intro k
    obtain ⟨M, hM⟩ : ∃ M, ∀ m ≤ M, slipface α a m ≥ k := by
      exact?;
    exact ⟨ M + 1, fun m hm => not_lt.1 fun contra => not_lt_of_ge ( hM m ( by linarith ) ) hm ⟩;
  intro k
  obtain ⟨M, hM⟩ : ∃ M, ∀ m, slipface α a m < k → m ≥ M := h_m_bounded_below k;
  -- Since $s_\beta(M, \ell_i) \to \infty$ as $\ell_i \to -\infty$, we can find $L$ such that for all $\ell \le L$, $s_\beta(M, \ell) \ge k$.
  obtain ⟨L, hL⟩ : ∃ L, ∀ ℓ ≤ L, slipface β M ℓ ≥ k := by
    exact?;
  use L;
  intro ℓ hℓ
  have h_star_ge_beta : ∀ m, slipface α a m + slipface β m ℓ ≥ k := by
    intro m
    by_cases hm : slipface α a m < k;
    · have h_beta_ge_beta_M : slipface β m ℓ ≥ slipface β M ℓ := by
        apply_rules [ Set.ncard_le_ncard ];
        · exact fun x hx => ⟨ hx.1, lt_of_lt_of_le hx.2 ( hM m hm ) ⟩;
        · exact?;
      linarith [ hL ℓ hℓ ];
    · linarith;
  exact le_csInf ⟨ _, ⟨ M, rfl ⟩ ⟩ fun x hx => by obtain ⟨ m, rfl ⟩ := hx; exact h_star_ge_beta m;

/-
The Demazure product `star_slipface α β ℓ b` goes to infinity as `ℓ → ∞`.
-/
lemma star_slipface_blows_up_at_pos_infty {α β : Equiv.Perm ℤ} (hα : IsASP α) (hβ : IsASP β) (b : ℤ) :
    ∀ k, ∃ L, ∀ ℓ ≥ L, star_slipface α β ℓ b ≥ k := by
      intro k
      obtain ⟨L₁, hL₁⟩ : ∃ L₁, ∀ ℓ ≥ L₁, slipface β ℓ b ≥ k + 1 := by
        exact?
      obtain ⟨L₂, hL₂⟩ : ∃ L₂, ∀ ℓ ≥ L₂, slipface α ℓ L₁ ≥ k + 1 := by
        exact?
      use Max.max L₁ L₂ + 1
      intro ℓ hℓ
      have hℓ₁ : ℓ ≥ L₁ := by
        linarith [ le_max_left L₁ L₂, le_max_right L₁ L₂ ]
      have hℓ₂ : ℓ ≥ L₂ := by
        linarith [ le_max_right L₁ L₂ ]
      have h_min : star_slipface α β ℓ b ≥ k + 1 := by
        -- Consider any $m$.
        have h_min_m : ∀ m, slipface α ℓ m + slipface β m b ≥ k + 1 := by
          intro m
          by_cases hm : m ≥ L₁;
          · exact le_add_of_nonneg_of_le ( Nat.zero_le _ ) ( hL₁ m hm );
          · have h_min_m : slipface α ℓ m ≥ slipface α ℓ L₁ := by
              apply Set.ncard_le_ncard;
              · exact fun x hx => ⟨ by linarith [ hx.1 ], hx.2 ⟩;
              · exact?;
            linarith [hL₂ ℓ hℓ₂];
        exact le_csInf ⟨ _, ⟨ L₁, rfl ⟩ ⟩ fun x hx => by aesop;
      linarith [h_min]

/-
Definitions of `IsSlipface` and `IsSubmodular` for functions `s : ℤ → ℤ → ℕ`.
`IsSlipface` requires the existence of a shift `χ` such that `s` satisfies Lipschitz conditions (S1), a lower bound (S2), and asymptotic behavior (S3).
`IsSubmodular` requires the mixed second difference to be non-negative.
-/
/-- A function `s : ℤ → ℤ → ℕ` is a slipface if it satisfies the conditions (S1)-(S3) from the paper. -/
def IsSlipface (s : ℤ → ℤ → ℕ) : Prop :=
  ∃ χ : ℤ,
    (∀ a b, s a b ≤ s (a + 1) b ∧ s (a + 1) b ≤ s a b + 1) ∧
    (∀ a b, s a (b + 1) ≤ s a b ∧ s a b ≤ s a (b + 1) + 1) ∧
    (∀ a b, (s a b : ℤ) ≥ max 0 (χ + a - b)) ∧
    (∀ b, {a | (s a b : ℤ) ≠ max 0 (χ + a - b)}.Finite) ∧
    (∀ a, {b | (s a b : ℤ) ≠ max 0 (χ + a - b)}.Finite)

/-- A function `s : ℤ → ℤ → ℕ` is submodular if it satisfies the submodularity condition. -/
def IsSubmodular (s : ℤ → ℤ → ℕ) : Prop :=
  ∀ a b, (s (a + 1) b : ℤ) - s a b - s (a + 1) (b + 1) + s a (b + 1) ≥ 0

/-
Recurrence relation for `slipface` in the first argument: $s_\alpha(a+1, b) - s_\alpha(a, b) = 1$ if $\alpha^{-1}(a) \ge b$, else 0.
-/
lemma slipface_succ_left {α : Equiv.Perm ℤ} (hα : IsASP α) (a b : ℤ) :
    (slipface α (a + 1) b : ℤ) - (slipface α a b : ℤ) = if α.symm a ≥ b then 1 else 0 := by
  rw [ show slipface α ( a + 1 ) b = Set.ncard { n | n ≥ b ∧ α n ≤ a } from ?_, show slipface α a b = Set.ncard { n | n ≥ b ∧ α n < a } from ?_ ];
  · rw [ show { n : ℤ | n ≥ b ∧ α n ≤ a } = { n : ℤ | n ≥ b ∧ α n < a } ∪ { n : ℤ | n ≥ b ∧ α n = a } from ?_, @Set.ncard_union_eq ];
    · split_ifs <;> simp_all +decide [ Set.ncard_eq_toFinset_card' ];
      · exact ⟨ α.symm a, Set.eq_singleton_iff_unique_mem.mpr ⟨ ⟨ by assumption, by simp +decide ⟩, fun n hn => α.injective <| by aesop ⟩ ⟩;
      · rw [ show { n | b ≤ n ∧ α n = a } = ∅ from Set.eq_empty_of_forall_notMem fun x hx => by obtain ⟨ hx₁, hx₂ ⟩ := hx; have := α.injective ( hx₂.trans ( Eq.symm ( show α ( α.symm a ) = a from α.apply_symm_apply a ) ) ) ; linarith [ hx₁, hx₂, this ] ] ; norm_num;
    · exact Set.disjoint_left.mpr fun x hx₁ hx₂ => hx₁.2.not_le hx₂.2.ge;
    · exact?;
    · exact Set.Finite.subset ( Set.finite_singleton ( α.symm a ) ) fun x hx => by have := hx.2; aesop;
    · ext n; simp [Set.mem_union, Set.mem_setOf_eq];
      grind;
  · exact?;
  · unfold slipface;
    norm_num [ Set.ext_iff, Int.lt_add_one_iff ]

/-
Recurrence relation for `slipface` in the second argument: $s_\alpha(a, b+1) - s_\alpha(a, b) = -1$ if $\alpha(b) < a$, else 0.
-/
lemma slipface_succ_right {α : Equiv.Perm ℤ} (hα : IsASP α) (a b : ℤ) :
    (slipface α a (b + 1) : ℤ) - (slipface α a b : ℤ) = if α b < a then -1 else 0 := by
  split_ifs <;> simp +decide [ *, slipface ];
  · rw [ show { n : ℤ | b ≤ n ∧ α n < a } = { n : ℤ | b + 1 ≤ n ∧ α n < a } ∪ { b } from ?_, @Set.ncard_union_eq ] <;> norm_num;
    · exact Set.Finite.subset ( slipface_finite hα a ( b + 1 ) ) fun x hx => ⟨ by linarith [ hx.1 ], hx.2 ⟩;
    · grind;
  · rw [ show { n : ℤ | b ≤ n ∧ ( α n ) < a } = { n : ℤ | b + 1 ≤ n ∧ ( α n ) < a } from ?_ ];
    · ring;
    · exact Set.ext fun x => ⟨ fun hx => ⟨ lt_of_le_of_ne hx.1 ( by rintro rfl; exact ‹¬α b < a› hx.2 ), hx.2 ⟩, fun hx => ⟨ by linarith [ hx.1 ], hx.2 ⟩ ⟩

/-
The shift of a permutation `α` is defined as `s_α(0, 0) - s_{α^{-1}}(0, 0)`.
-/
/-- The shift of a permutation `α`. -/
noncomputable def shift (α : Equiv.Perm ℤ) : ℤ :=
  (slipface α 0 0 : ℤ) - (slipface α.symm 0 0 : ℤ)

/-
If a permutation `f` is almost-sign-preserving, then its inverse `f.symm` is also almost-sign-preserving.
-/
lemma IsASP_symm {f : Equiv.Perm ℤ} (h : IsASP f) : IsASP f.symm := by
  exact Set.Finite.subset ( h.image f ) fun x hx => by aesop;

/-
Checking if `shift` is available.
-/
#check shift

/-
The duality identity for slipfaces: $s_\alpha(a, b) - s_{\alpha^{-1}}(b, a) = \chi_\alpha + a - b$.
-/
lemma slipface_duality {α : Equiv.Perm ℤ} (hα : IsASP α) (a b : ℤ) :
    (slipface α a b : ℤ) - (slipface α.symm b a : ℤ) = shift α + a - b := by
      -- Applying the recurrence relations, we need to show that $f(a+1, b) = f(a, b)$ and $f(a, b+1) = f(a, b)$.
      have h_recurrence : ∀ a b : ℤ, (slipface α (a + 1) b : ℤ) - (slipface α.symm b (a + 1) : ℤ) - (a + 1) + b = (slipface α a b : ℤ) - (slipface α.symm b a : ℤ) - a + b := by
        intro a b; have := slipface_succ_left hα a b; have := slipface_succ_right ( IsASP_symm hα ) b a; simp_all +decide [ sub_eq_iff_eq_add' ] ;
        split_ifs <;> linarith;
      have h_recurrence_b : ∀ a b : ℤ, (slipface α a (b + 1) : ℤ) - (slipface α.symm (b + 1) a : ℤ) - a + (b + 1) = (slipface α a b : ℤ) - (slipface α.symm b a : ℤ) - a + b := by
        intros a b
        have := slipface_succ_right hα a b
        have := slipface_succ_right (IsASP_symm hα) b a
        simp_all +decide [ sub_eq_iff_eq_add ];
        have := slipface_succ_left ( IsASP_symm hα ) b a; simp_all +decide [ sub_eq_iff_eq_add ] ;
        split_ifs <;> linarith;
      induction' a using Int.induction_on with a IH a IH ; induction' b using Int.induction_on with b IH' b IH' ; aesop;
      · grind;
      · grind;
      · linarith [ h_recurrence a b ];
      · grind

/-
The duality identity for slipfaces: $s_\alpha(a, b) - s_{\alpha^{-1}}(b, a) = \chi_\alpha + a - b$.
-/
lemma slipface_duality_thm {α : Equiv.Perm ℤ} (hα : IsASP α) (a b : ℤ) :
    (slipface α a b : ℤ) - (slipface α.symm b a : ℤ) = shift α + a - b := by
      exact?

/-
The duality identity for slipfaces: $s_\alpha(a, b) - s_{\alpha^{-1}}(b, a) = \chi_\alpha + a - b$.
-/
lemma slipface_duality_eq {α : Equiv.Perm ℤ} (hα : IsASP α) (a b : ℤ) :
    (slipface α a b : ℤ) - (slipface α.symm b a : ℤ) = shift α + a - b := by
      exact?

/-
The duality identity for slipfaces: $s_\alpha(a, b) - s_{\alpha^{-1}}(b, a) = \chi_\alpha + a - b$.
-/
lemma slipface_duality_final {α : Equiv.Perm ℤ} (hα : IsASP α) (a b : ℤ) :
    (slipface α a b : ℤ) - (slipface α.symm b a : ℤ) = shift α + a - b := by
      exact?

/-
The slipface function of an ASP permutation satisfies the `IsSlipface` conditions.
-/
lemma slipface_is_slipface {α : Equiv.Perm ℤ} (hα : IsASP α) :
    IsSlipface (slipface α) := by
  refine' ⟨ shift α, _, _, _, _, _ ⟩;
  · intro a b;
    have := slipface_succ_left hα a b;
    split_ifs at this <;> constructor <;> linarith;
  · intro a b;
    -- By definition of slipface, we know that $s_\alpha(a, b+1) \leq s_\alpha(a, b)$ and $s_\alpha(a, b) \leq s_\alpha(a, b+1) + 1$ follow directly from the properties of the slipface function.
    have h_slipface_right : (slipface α a (b + 1) : ℤ) - (slipface α a b : ℤ) = if α b < a then -1 else 0 := by
      exact?;
    split_ifs at h_slipface_right <;> constructor <;> linarith;
  · -- By definition of $shift$, we know that $s(a, b) = s_{\alpha^{-1}}(b, a) + \chi_\alpha + a - b$.
    have h_shift : ∀ a b : ℤ, (slipface α a b : ℤ) = (slipface α.symm b a : ℤ) + shift α + a - b := by
      exact fun a b => by linarith [ slipface_duality_thm hα a b ] ;
    grind;
  · intro b;
    -- For large $a$, $s_\alpha(a, b) = \chi + a - b$.
    have h_large_a : ∃ L, ∀ a ≥ L, slipface α a b = shift α + a - b := by
      have h_large_a : ∃ L, ∀ a ≥ L, slipface α.symm b a = 0 := by
        apply slipface_vanishes_at_pos_infty;
        exact?;
      obtain ⟨ L, hL ⟩ := h_large_a; use L; intros a ha; linarith [ slipface_duality_thm hα a b, hL a ha ] ;
    -- For small $a$, $s_\alpha(a, b) = 0$.
    have h_small_a : ∃ L, ∀ a ≤ L, slipface α a b = 0 := by
      have := slipface_vanishes_at_neg_infty hα b;
      tauto;
    refine' Set.Finite.subset ( Set.finite_Icc ( h_small_a.choose : ℤ ) ( h_large_a.choose : ℤ ) ) _;
    intro a ha;
    constructor <;> contrapose! ha;
    · have := h_small_a.choose_spec a ha.le;
      have := slipface_duality_thm hα a b;
      grind;
    · have := h_large_a.choose_spec a ha.le;
      grind;
  · intro a;
    -- By definition of `shift`, we know that `shift α + a - b` is finite for fixed `a`.
    have h_shift_finite : ∃ L, ∀ b ≤ L, slipface α a b = max 0 (shift α + a - b) := by
      -- Choose $L$ such that for all $b \leq L$, $s_{\alpha^{-1}}(b, a) = 0$.
      obtain ⟨L, hL⟩ : ∃ L, ∀ b ≤ L, slipface α.symm b a = 0 := by
        convert slipface_vanishes_at_neg_infty _ a using 1;
        exact?;
      use L;
      intro b hb;
      have := slipface_duality_thm hα a b;
      grind;
    have h_shift_finite : ∃ L, ∀ b ≥ L, slipface α a b = max 0 (shift α + a - b) := by
      obtain ⟨L, hL⟩ : ∃ L, ∀ b ≥ L, slipface α a b = 0 := by
        exact?;
      use Max.max L (shift α + a + 1);
      grind;
    obtain ⟨ L₁, hL₁ ⟩ := ‹∃ L, ∀ b ≤ L, _›; obtain ⟨ L₂, hL₂ ⟩ := h_shift_finite; exact Set.Finite.subset ( Set.finite_Icc L₁ L₂ ) fun x hx => ⟨ not_lt.mp fun contra => hx <| hL₁ x contra.le, not_lt.mp fun contra => hx <| hL₂ x contra.le ⟩ ;

/-
The duality identity for slipfaces: $s_\alpha(a, b) - s_{\alpha^{-1}}(b, a) = \chi_\alpha + a - b$.
-/
lemma slipface_duality_prop {α : Equiv.Perm ℤ} (hα : IsASP α) (a b : ℤ) :
    (slipface α a b : ℤ) - (slipface α.symm b a : ℤ) = shift α + a - b := by
      exact?

/-
The duality identity for slipfaces: $s_\alpha(a, b) - s_{\alpha^{-1}}(b, a) = \chi_\alpha + a - b$.
-/
lemma slipface_duality_v2 {α : Equiv.Perm ℤ} (hα : IsASP α) (a b : ℤ) :
    (slipface α a b : ℤ) - (slipface α.symm b a : ℤ) = shift α + a - b := by
      convert slipface_duality hα a b using 1