name = "demazure"
version = "1.1.1"
keywords = ["math"]
defaultTargets = ["Demazure"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc4"

[[lean_lib]]
name = "Demazure"
